name = "Cartographer"
uuid = "d6ea422f-1f55-4be1-bfc3-e7c09aa4d855"
authors = ["brendanjohnharris <bhar9988@uni.sydney.edu.au> and contributors"]
version = "1.0.0-DEV"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[weakdeps]
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"

[extensions]
ProgressLoggingExt = ["ProgressLogging"]

[compat]
Distributed = "1.11.0"
UUIDs = "1.11.0"
julia = "1.10"
